name: CICD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU for platforms
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Build Docker image
        run: docker buildx build --platform linux/arm64 -t myappimage:v2 -f Dockerfile . --push --progress=plain
